-- 2. Daily Analysis Reports (Cloud Data Mart)
-- Stores the LATEST processed "Insight" for a specific ticker.
-- Latest-Only Policy: Keeps only 1 row per ticker to optimize space.
CREATE TABLE IF NOT EXISTS daily_analysis_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL, -- Report Date (matches newest data point)
    ticker TEXT NOT NULL,
    
    -- Analysis Result (JSON)
    -- Structure:
    -- {
    --   "signal": "Golden Cross",
    --   "summary": "...",
    --   "supply_chart": [ ...last 60 days data... ],
    --   "metrics": { "foreigner_5d_net": ..., ... }
    -- }
    report_data JSONB NOT NULL,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Optimized constraint for Latest-Only policy
    UNIQUE(ticker)
);

-- 3. Algo Picks (Discovery)
-- Algorithmic "Recommended Lists" generated by the Admin Tool.
CREATE TABLE IF NOT EXISTS algo_picks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    
    -- Pick Category (e.g., "Value_Picks", "Twin_Engines", "Trend_Following")
    strategy_name TEXT NOT NULL, 
    
    tickers TEXT[] NOT NULL, -- Array of tickers ['005930', '000660']
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    -- Optimized constraint for Latest-Only policy
    UNIQUE(strategy_name)
);

-- RLS Policies
ALTER TABLE daily_analysis_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE algo_picks ENABLE ROW LEVEL SECURITY;

-- Read Access
CREATE POLICY "Public Read Reports" ON daily_analysis_reports FOR SELECT USING (true);
CREATE POLICY "Public Read Algo Picks" ON algo_picks FOR SELECT USING (true);

-- Admin Tool Access (via Service Role)
CREATE POLICY "Service Role Full Access" ON daily_analysis_reports USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Algo Picks" ON algo_picks USING (true) WITH CHECK (true);
