-- 2. Daily Analysis Reports (Cloud Data Mart)
-- Stores the processed "Insight" for a specific ticker for a specific day.
-- This is what the Web UI reads to show the "Daily Briefing".

CREATE TABLE IF NOT EXISTS daily_analysis_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL, -- Report Date
    ticker TEXT NOT NULL,
    
    -- Analysis Result (JSON)
    -- Structure:
    -- {
    --   "status": "HOLD" | "BUY" | "SELL",
    --   "signal": "Golden Cross",
    --   "summary": "...",
    --   "supply_chart": [ ...last 30 days data... ],
    --   "technical_score": 80
    -- }
    report_data JSONB NOT NULL,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Unique constraint to prevent duplicate reports for same ticker/day
    UNIQUE(date, ticker)
);

-- 3. Guru Picks (Discovery)
-- Publicly shared "Recommended Lists" generated by the Admin Tool.

CREATE TABLE IF NOT EXISTS guru_picks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    
    -- Pick Category (e.g., "Graham_Value", "ONeil_Growth", "Golden_Cross")
    strategy_name TEXT NOT NULL, 
    
    tickers TEXT[] NOT NULL, -- Array of tickers ['005930', '000660']
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, strategy_name)
);

-- RLS Policies
ALTER TABLE daily_analysis_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE guru_picks ENABLE ROW LEVEL SECURITY;

-- Everyone can read (Public/Shared or Auth users)
CREATE POLICY "Public Read Reports" ON daily_analysis_reports FOR SELECT USING (true);
CREATE POLICY "Public Read Guru Picks" ON guru_picks FOR SELECT USING (true);

-- Only Service Role (Admin Tool) can Insert/Update
-- (In Supabase, Service Role bypasses RLS, but explicit policy is good practice or strictly 'false' for anon)
CREATE POLICY "Service Role Full Access" ON daily_analysis_reports USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access Picks" ON guru_picks USING (true) WITH CHECK (true);
